### ISSUE TITLE
傲来操作系统（EulixOS）训练营

### ISSUE THREAD

**Issue by Nomop** [Lemonadeccc/Awesome-Events#3]
中科院举办2024/06举办的的RISC-V的训练营，这是第一次办，明年应该应该也会有。
https://opencamp.cn/EulixOS/camp/202401

**Comment by Lemonadeccc** [comment]
直接fork然后提pr吧，我直接改也不太合适，这算是你提出来的。如果使用https://opencamp.cn/的话更好，这页面还有其他的OS活动。

**Comment by Lemonadeccc** [comment]
> 中科院举办2024/06举办的的RISC-V的训练营，这是第一次办，明年应该应该也会有。 https://opencamp.cn/EulixOS/camp/202401
直接fork然后提pr吧，我直接改也不太合适，这算是你提出来的。如果使用[https://opencamp.cn/的话更好，这页面还有其他的OS活动。](https://opencamp.cn/%E7%9A%84%E8%AF%9D%E6%9B%B4%E5%A5%BD%EF%BC%8C%E8%BF%99%E9%A1%B5%E9%9D%A2%E8%BF%98%E6%9C%89%E5%85%B6%E4%BB%96%E7%9A%84OS%E6%B4%BB%E5%8A%A8%E3%80%82)
